name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: docker://mcr.microsoft.com/dotnet/core/samples:dotnetapp
      with:
        entrypoint: /app/dotnet
        args: dotnetapp.dll
